version: '3.1'

services:
  db:
    image: mongo:4
    volumes:
      - ./data:/data/db

  web:
    image: node:10
    user: "node"
    working_dir: /usr/app
    volumes:
      - ./web:/usr/app/
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: "npm run docker"
    depends_on:
      - db
    links:
      - db

  dbadmin:
    image: mongo-express
    depends_on:
      - db
    external_links:
      - db:mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: tototutu123
